.Dd 19th of October 2016
.Dt DARKSTAR-PACKNAME 1 darkstar-tools-14.2
.Sh NAME
.Nm darkstar-packname
.Nd extract package information from filename
.Sh SYNOPSIS
.Nm darkstar-packname
.Op Fl v | Fl b
.Ar filename ...
.Sh DESCRIPTION
.Nm
extracts package information from slackware package filenames that adheres to
the <name>-<version>-<arch>-<build><tag>[.ext] format, where
ext is one of tgz, txz, tbz or tlz, and only the name part may contain a '-'.
Any leading path is ignored.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl b 
Print package basename, without extension.
.It Fl v 
Print package version

.Sh SEE ALSE
.Xr darkstar-installed 1 ,
