.Dd 16th of April 2014
.Dt DARKSTAR-NOTINPKG 1 darkstar-tools-14.2
.Sh NAME
.Nm darkstar-notinpkg
and
.Nm darkstar-notonsys
.Nd compares file list between files on the system and files that
are installed according to the package database
.Sh SYNOPSIS
.Nm darkstar-notinpkg
.Nm darkstar-notonsys
.Sh DESCRIPTION
.Nm darkstar-notinpkg
prints files that are present on the / filesystem that doesn't belong to any package.

.Nm darkstar-notonsys
prints files that have been installed with some package, but aren't
present on the system.

.Sh SEE ALSE
.Xr darkstar-installed 1 ,
.Xr darkstar-packcontent 1 ,
