.Dd 17th of April 2014
.Dt DARKSTAR-INSTALLED 1 darkstar-tools-14.2
.Sh NAME
.Nm darkstar-installed
.Nd querys the package database for installed packages
.Sh SYNOPSIS
.Nm darkstar-installed
.Ar pkgname ...
.Sh DESCRIPTION
.Nm
looks in /var/log/packages for installed packages and prints the path
to the database file for the corresponding package, if found.
.Sh ARGUMENTS
.Ar package name
may be a package filename, e.g. "nc-1.10-x86_64-1.txz" or a package
basename, e.g. "xz-5.0.5-x86_64-1", either optionally with a leading path,
or simply a package name, e.g. "xz" or "glibc-solibs".
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
All packages are installed
.It 1
Any package is not installed, or error.

.Sh SEE ALSE
.Xr darkstar-packname 1 ,
.Xr darkstar-packcontent 1 .
