.Dd February 15, 2015
.Dt DARKSTAR-DEPTREE 1 darkstar-tools-14.1
.Sh NAME
.Nm darkstar-deptree
.Nd Print a tree of dependencies
.Sh SYNOPSIS
.Nm
.Op Pa package ...
.Sh DESCRIPTION
.Nm
prints a tree of package dependencies. Package
.Pa A
is determined to
depend on package
.Pa B
iff
.Pa A
contains an executable file that is dynamically linked agains
some library found in
.Pa B .
The files in
.Pa /var/log/packages
are read to find which package a file belongs to.
And
.Xr darkstar-makedep 1
is used to the build the dependancy tree.

By default trees will be printed with packages that don't depend
on any other as roots (ought to be glibc). Unless some
.Pa packages
are given as arguments, in which case, they will be used as roots,
and the trees will be printed "upside down", with the proper roots
(libc) as leafs.

.Sh AUTHOR
Written by Lars Lindqvist.
.Sh COPYRIGHT
Copyright (C) 2013-2015 Lars Lindqvist
.Sh LICENSE
Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
.Sh WARRANTY
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

.Sh SEE ALSE
.Xr darkstar-makedep 1 ,
.Xr elfdeps 1 .
