.Dd 19th of October 2016
.Dt DARKSTAR-PACKCONTENT 1 darkstar-tools-14.2
.Sh NAME
.Nm darkstar-packcontent
.Nd prints content of installed package(s)
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl e | Fl m
.Pa pkg ...
.Nm
.Pa -f file-regex
.Sh DESCRIPTION
.Nm
prints information about the files belonging to an installed package.
It reads the the "FILE LIST:" section of a packge, and can find out if
a file or directory is still present on the system or not, and compute
the actual installed size of a package.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl v
Verbose output, prepend lines with "<package name>:"
.It Fl e
Print only existing files.
.It Fl m
Print only missing files.
.It Fl f 
Print files matching
.Pa regex
and the package(s) owning them, for those who are too lazy to:
.Bd -literal -offset indent
$ grep regex /var/log/packages/*
.Sh NOTES
The /install directory is always ignored, since it should never actually
stay on the file system when a package has been properly installed.

The ".new" suffix gets stripped from filenames, since install/doinst.sh
will rename such files on a clean system, might cause false results.

To accommodate glibc{,-solibs} lib/incoming/ and lib64/incoming/ are
truncated to lib/ and lib64/, respectively.

.Sh SEE ALSE
.Xr darkstar-installed 1 ,
