.Dd April 16, 2014
.Dt DARKSTAR-NOTINPKG 1 darkstar-tools-14.1
.Sh NAME
.Nm darkstar-notinpkg
and
.Nm darkstar-notonsys
.Nd compares file list between files on the system and files that
are installed according to the package database
.Sh SYNOPSIS
.Nm darkstar-notinpkg
.Nm darkstar-notonsys
.Sh DESCRIPTION
.Nm darkstar-notinpkg
prints files that are present on the /, /opt and /usr filesystems,
that doesn't belong to any package.

.Nm darkstar-notonsys
prints files that have been installed with some package, but aren't
present on the system.
.Sh NOTES
Only files on the same device as /, /opt or /usr are regarded as being
actually installed (see 
.Fl xdev
in
.Xr find 1 ), but the content of /root and /var/{log,run,cache,tmp,spool}
are ignored, since they may contain a lot of non-packaged files.

See
.Xr darkstar-packcontent 1 ,
for further information on which files are regarded as having been installed
with a package.

.Sh AUTHOR
Written by Lars Lindqvist.
.Sh COPYRIGHT
Copyright (C) 2010-2014 Lars Lindqvist
.Sh LICENSE
Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
.Sh WARRANTY
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

.Sh SEE ALSE
.Xr darkstar-installed 1 ,
.Xr darkstar-packcontent 1 ,
