.Dd 7th of February 2015
.Dt MKSLACK-DESC 1 darkstar-tools-14.2
.Sh NAME
.Nm mkslack-desc
.Nd creates compliant (touch wood) slack-desc
.Sh SYNOPSIS
.Nm mkslack-desc
.Ar package-name
.Ar short-description
.Sh DESCRIPTION
.Nm mkslack-desc
reads (long) package description from standard input and prints proper slackware
package description to standard output.
.Sh ARGUMENTS
.Bl -tag -width Ds
.It Ar package-name
Exact name of the package (excluding version, arch, build).
.It Ar short-descrition
Short description, excluding parentesis
